### ISSUE TITLE
./gradlew check : java.util.ServiceConfigurationError: Locale provider adapter "CLDR"cannot be instantiated.

### ISSUE THREAD

**Issue by lindenb** [nextflow-io/nf-hello#17]
cross-posted on slack: https://nextflow.slack.com/archives/C02T98BKE2K/p1709894909502359

I tried to compile the hello plugin but I got the following error/stacktrace:

```
$ ./gradlew check

> Task :plugins:nf-hello:compileGroovy FAILED
java.util.ServiceConfigurationError: Locale provider adapter "CLDR"cannot be instantiated.
        at java.base/sun.util.locale.provider.LocaleProviderAdapter.forType(LocaleProviderAdapter.java:200)
  (...)
        ... 12 more
Caused by: java.lang.IllegalArgumentException: newLimit > capacity: (55346993 > 27910144)
        at java.base/java.nio.Buffer.createLimitException(Buffer.java:398)
        at java.base/java.nio.Buffer.limit(Buffer.java:372)
        at java.base/java.nio.ByteBuffer.limit(ByteBuffer.java:1539)
        at java.base/java.nio.MappedByteBuffer.limit(MappedByteBuffer.java:331)
        at java.base/java.nio.MappedByteBuffer.limit(MappedByteBuffer.java:73)
        at java.base/jdk.internal.jimage.BasicImageReader.slice(BasicImageReader.java:213)
        at java.base/jdk.internal.jimage.BasicImageReader.readBuffer(BasicImageReader.java:372)
        at java.base/jdk.internal.jimage.BasicImageReader.getResourceBuffer(BasicImageReader.java:438)
        at java.base/jdk.internal.jimage.ImageReader.getResourceBuffer(ImageReader.java:199)
        at java.base/jdk.internal.module.SystemModuleFinders$SystemModuleReader.read(SystemModuleFinders.java:485)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:809)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:741)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClass(BuiltinClassLoader.java:621)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:633)
        at java.base/java.lang.Class.forName(Class.java:584)
        at java.base/java.lang.Class.forName(Class.java:559)
        at java.base/java.util.ServiceLoader.loadProvider(ServiceLoader.java:859)
        at java.base/java.util.ServiceLoader$ModuleServicesLookupIterator.hasNext(ServiceLoader.java:1084)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
        at java.base/sun.util.cldr.CLDRLocaleProviderAdapter.lambda$new$0(CLDRLocaleProviderAdapter.java:84)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at java.base/sun.util.cldr.CLDRLocaleProviderAdapter.<init>(CLDRLocaleProviderAdapter.java:83)
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
        ... 15 more

FAILURE: Build failed with an exception.
```

I googled the error message but I don't really understand what I saw. My local javac version is avac 17.0.3.1.
Any idea ?

**Comment by lindenb** [comment]
there is no problem with the previous version:

```
$ ./gradlew check

> Task :plugins:nf-hello:test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v9.Java9 (file:/home/lindenb/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/3.0.12/b20d66980463bc4944b5537306c15abf38adbf72/groovy-3.0.12.jar) to method sun.nio.fs.UnixFileSystem.provider()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v9.Java9
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

BUILD SUCCESSFUL in 19s
4 actionable tasks: 2 executed, 2 up-to-date
```

**Comment by pditommaso** [comment]
Unable to replicate. Are you trying with the laster master version [f686fbc](https://github.com/nextflow-io/nf-hello/commit/f686fbcf2346f3fc02b2288f567c016ab6bf2e50)?

**Comment by lindenb** [comment]
@pditommaso  I tried on another server, it works now :thinking:

**Comment by lindenb** [comment]
A note about this: 

In changed gradle/wrapper/gradle-wrapper.properties I changed gradle-8.4-bin.zip to gradle-8.9-bin.zip and there is no more error.
